CREATE TABLE country
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255) NOT NULL,
    continent VARCHAR(255) NOT NULL
);


CREATE TABLE author
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    surname    VARCHAR(255) NOT NULL,
    country_id BIGINT,
    FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE SET NULL
);


CREATE TABLE book
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255) NOT NULL,
    category  VARCHAR(255) NOT NULL, -- Assuming BookCategory is a String enum
    author_id BIGINT,
    FOREIGN KEY (author_id) REFERENCES author (id) ON DELETE SET NULL
);


CREATE TABLE book_copy
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id   BIGINT  NOT NULL,
    is_loaned BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE CASCADE
);


CREATE TABLE book_history
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255) NOT NULL,
    category  VARCHAR(255) NOT NULL, -- Assuming BookCategory is a String enum
    author_id BIGINT,
    FOREIGN KEY (author_id) REFERENCES author (id) ON DELETE CASCADE
);


CREATE TABLE shop_users
(
    username                   VARCHAR(255) PRIMARY KEY,
    password                   VARCHAR(255) NOT NULL,
    name                       VARCHAR(255) NOT NULL,
    surname                    VARCHAR(255) NOT NULL,
    role                       VARCHAR(255) NOT NULL, -- Assuming Role is a String enum
    is_account_non_expired     BOOLEAN      NOT NULL DEFAULT TRUE,
    is_account_non_locked      BOOLEAN      NOT NULL DEFAULT TRUE,
    is_credentials_non_expired BOOLEAN      NOT NULL DEFAULT TRUE,
    is_enabled                 BOOLEAN      NOT NULL DEFAULT TRUE
);



INSERT INTO shop_users (username, password, name, surname, role)
VALUES ('li',
        '$2a$10$s6a4wIH30XUqHYg6YcZGS.WshLLVeXTmEiKw4yDyLtQNkhpuICeVy',
        'Snezana',
        'Koleva',
        'ROLE_LIBRARIAN');

-- private Long id;
-- private String token;
-- private LocalDateTime issuedAt;
-- private LocalDateTime expiresAt;
CREATE TABLE book_readers
(
    book_id       BIGINT       NOT NULL,
    user_username VARCHAR(255) NOT NULL,
    PRIMARY KEY (book_id, user_username),
    FOREIGN KEY (book_id) REFERENCES book (id),
    FOREIGN KEY (user_username) REFERENCES shop_users (username)
);

create table jwt_logs
(

    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token      varchar not null,
    issued_at  varchar,
    expires_at varchar

);

INSERT INTO country (name, continent)
VALUES ('USA', 'North America'),
       ('UK', 'Europe'),
       ('France', 'Europe'),
       ('Japan', 'Asia'),
       ('Brazil', 'South America'),
       ('Australia', 'Oceania'),
       ('India', 'Asia'),
       ('Canada', 'North America'),
       ('Germany', 'Europe'),
       ('South Africa', 'Africa');

INSERT INTO author (name, surname, country_id)
VALUES ('John', 'Doe', 1),
       ('Jane', 'Austen', 2),
       ('Victor', 'Hugo', 3),
       ('Haruki', 'Murakami', 4),
       ('Paulo', 'Coelho', 5),
       ('Margaret', 'Atwood', 6),
       ('Arundhati', 'Roy', 7),
       ('Alice', 'Munro', 8),
       ('Hermann', 'Hesse', 9),
       ('Chinua', 'Achebe', 10);



INSERT INTO book (name, category, author_id)
VALUES ('The Great Adventure', 'NOVEL', 1),
       ('Pride and Prejudice', 'CLASSICS', 2),
       ('Les Misérables', 'HISTORY', 3),
       ('Kafka on the Shore', 'FANTASY', 4),
       ('The Alchemist', 'NOVEL', 5),
       ('The Handmaids Tale', 'DRAMA', 6),
       ('The God of Small Things', 'DRAMA', 7),
       ('Dear Life', 'NOVEL', 8),
       ('Siddhartha', 'CLASSICS', 9),
       ('Things Fall Apart', 'HISTORY', 10),
       ('Invisible Man', 'NOVEL', 1),
       ('Emma', 'CLASSICS', 2),
       ('The Hunchback of Notre-Dame', 'HISTORY', 3),
       ('Norwegian Wood', 'NOVEL', 4),
       ('Brida', 'BIOGRAPHY', 5),
       ('Oryx and Crake', 'THRILLER', 6),
       ('The Ministry of Utmost Happiness', 'DRAMA', 7),
       ('Runaway', 'NOVEL', 8),
       ('Steppenwolf', 'CLASSICS', 9),
       ('No Longer at Ease', 'HISTORY', 10);

ALTER TABLE book
    DROP CONSTRAINT book_author_id_fkey,
    ADD CONSTRAINT book_author_id_fkey FOREIGN KEY (author_id) REFERENCES author (id) ON DELETE CASCADE;

DELETE FROM book WHERE author_id IS NULL;


ALTER TABLE author
    DROP CONSTRAINT author_country_id_fkey,
    ADD CONSTRAINT author_country_id_fkey FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE CASCADE;