apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: emt-project
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 32345
  selector:
    app: postgres