name: Full Stack CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install frontend dependencies
        working-directory: ./EMT-frontend
        run: npm install

      - name: Build frontend
        working-directory: ./EMT-frontend
        run: npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        run: |
          docker build --platform=linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/emt-backend:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/emt-backend:${{ github.sha }}

      - name: Build and push frontend Docker image
        working-directory: ./EMT-frontend
        run: |
          docker build --platform=linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/emt-frontend:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/emt-frontend:${{ github.sha }}
